$schema: "http://json-schema.org/draft-06/schema#"

description: snakemake configuration file

type: object

properties:
  sequences:
    type: string
  metadata:
    type: string
  inputs:
    type:
      - array
      - string # string values will be ignored, but this can be useful for cmd-line overrides
    minItems: 1
    items:
      type: object
      required:
        - name
        - metadata